# Stage 1: Build the Go application
FROM golang:1.20-alpine AS builder

WORKDIR /app

# Install git, which is required by `go mod tidy` for some modules (e.g., those from gopkg.in or direct Git repos)
RUN apk add --no-cache git

# Copy only go.mod. go.sum will be generated by `go mod tidy` inside the container.
COPY go.mod .

# Run go mod tidy to download dependencies and generate go.sum inside the container.
# This ensures all dependencies are resolved and go.sum is up-to-date within the build.
RUN go mod tidy

# Copy the rest of the application source code AFTER dependencies are handled
COPY . .

# Build the Go application
# CGO_ENABLED=0 is important for static binaries in Alpine
ENV CGO_ENABLED=0
ENV GOOS=linux
RUN go build -o /app/smtp-mailer ./main.go

# Stage 2: Create the final lean image
FROM alpine:latest

WORKDIR /app

# Install ca-certificates for HTTPS/TLS connections (needed for TLS connections to SMTP servers)
RUN apk add --no-cache ca-certificates

# Copy the built Go binary from the builder stage
COPY --from=builder /app/smtp-mailer .

# Copy the web assets and migrations
COPY web ./web
COPY database/migrations ./database/migrations

# Expose the port the application will listen on
EXPOSE 8080

# Command to run the executable
CMD ["/app/smtp-mailer"]