version: '3.8'

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: mailerdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mailer_net

  app:
    build: .
    restart: always
    expose:
      - "8080" # Expose port 8080 ONLY to other services in the network (like Caddy)
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - mailer_net

  caddy:
    image: caddy:2-alpine
    restart: always
    ports:
      - "80:80"   # For HTTP and automatic HTTP->HTTPS redirects
      - "443:443" # For HTTPS
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile # Mount your Caddyfile into the container
      - caddy_data:/data                 # Persist certificates and other Caddy data
      - caddy_config:/config
    networks:
      - mailer_net

networks:
  mailer_net:
    driver: bridge

volumes:
  postgres_data:
  caddy_data:
  caddy_config: