version: '3.8'

services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: mailerdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Optional: Expose DB port if you need to connect from host

  app:
    build: .
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db
    # Ensure the database is ready before the app starts
    healthcheck:
      # The '-h db' flag tells pg_isready which host to check inside the Docker network.
      test: ["CMD-SHELL", "pg_isready -U user -d mailerdb -h db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: